[package]
name = "ai-deno"
edition = "2021"

[lib]
name = "ai_deno"
crate-type = ["cdylib", "staticlib"]

[dependencies]
ffi-support = "0.4.4"
rustyscript = {git = "https://github.com/rscarson/rustyscript.git", features = ["all_extensions", "node_experimental"] }
hyper-util = "=0.1.7"
# rustyscript = { path = "../rustyscript", default-features = false, features = ["all_extensions", "node_experimental"] }
once_cell = "1.20.3"

[build-dependencies]
cbindgen = "0.28.0"