[package]
name = "ai-deno"
edition = "2021"
version = "0.1.0"

[lib]
name = "ai_deno"
crate-type = ["cdylib", "staticlib"]

[dependencies]
ffi-support = "0.4.4"
#rustyscript = {git = "https://github.com/rscarson/rustyscript.git", features = ["all_extensions", "node_experimental"] }
# rustyscript = { path = "../rustyscript", default-features = false, features = ["all_extensions", "node_experimental"] }
once_cell = "1.20.3"
anyhow = "1.0.95"
serde = "1.0.217"

winapi = "0.3.9"

maybe_path = { version = "0.1.3" }
deno_error = { version = "0.5.5" }
deno_core = { version = "0.336.0" }
deno_runtime = { version = "0.198.0", features = ["transpile"] }
deno_npm = { version = "0.27.2" }
deno_lib = { version = "0.6.0" }
node_resolver = { version = "0.28.0" }
deno_resolver = { version = "0.21.0", features = ["sync"] }
deno_ast = { version = "0.44.0", features = ["transpiling"] }
deno_path_util = { version = "0.3.1" }
#deno_cache      = { version = "0.121.0", optional = true }
#deno_console    = { version = "0.189.0", optional = true }
#deno_cron       = { version = "0.69.0", optional = true }
#deno_crypto     = { version = "0.203.0", optional = true }
#deno_fetch      = { version = "0.213.0", optional = true }
#deno_ffi        = { version = "0.176.0", optional = true }
#deno_fs         = { version = "0.99.0", optional = true, features = ["sync_fs"] }
#deno_http       = { version = "0.187.0", optional = true }
#deno_kv         = { version = "0.97.0", optional = true }
#deno_net        = { version = "0.181.0", optional = true }
#deno_node       = { version = "0.127.0", optional = true }
#deno_telemetry  = { version = "0.11.0", optional = true }
#deno_tls        = { version = "0.176.0", optional = true }
#deno_url        = { version = "0.189.0", optional = true }
#
#deno_web        = { version = "0.220.0", optional = true }
#deno_webidl     = { version = "0.189.0", optional = true }
#deno_webstorage = { version = "0.184.0", optional = true }
#deno_websocket  = { version = "0.194.0", optional = true }
#deno_webgpu     = { version = "0.156.0", optional = true }

#deno_io = { version = "0.99.0", optional = true }
#deno_os =  { version = "0.6.0", optional = true }

tokio = { version = "1.43.0", features = ["full"] }
tokio-util = "0.7.13"
thiserror = "2.0.11"
homedir = { version = "0.3.4" }
sys_traits = { version = "0.1.7", features = ["real", "default"] }
# deno_module_loader = { path = "../deno-module-loader" }

[build-dependencies]
cbindgen = "0.28.0"

[[example]]
name = "example"
crate-type = ["bin"]
